### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by juliocspires** [ymwdalex/paper-rock-scissors#2]
**Step 1:** Git Clone
**Step 2:** python train_simple_cnn.py
**Step 3:** python classification.py -type simple

Traceback (most recent call last):
  File "classification.py", line 112, in <module>
    classify(arguments.model_type)
  File "classification.py", line 67, in classify
    hand_img_resize = resize_from_array(hand_img, width, height)
  File "/home/X/Desktop/paper-rock-scissors/utils.py", line 43, in resize_from_array
    image = Image.fromarray(hand_img_array)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2313, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2266, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2199, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 751, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

**Comment by ymwdalex** [comment]
Hi juliocspires, thanks for reporting this. Is there any problem with using your webcam?
